name: test-f
on: 
  push:
    branches: tp3
    tags: 
      - v5
    paths: 
      - '.github/workflows/test-f.yml'
      - 'fonctionnel.md'
      - '.github/workflows/Fichier-tests-f.txt'
      - '.github/workflows/tests-f.sh'
      
jobs:
  job_id:
    name: Tests fonctionnels du TP3
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
       - uses: actions/checkout@v2
         with:
          persist-credentials: false 
          fetch-depth: 0

       - name: setup env
         run: |
           chmod +rwx .
           sudo apt update
           sudo apt install build-essential

       - name: verification version
         run: |
           echo $OSTYPE
           lsb_release -a 
           gcc -v >& gcc.txt
           cat gcc.txt
           
       - name: compilation
         run: |
          pwd
          make clean
          make
          ls -lash
             
       - name: tests
         run: |
           bash .github/workflows/tests-f.sh 
           make clean
           
       - name: Config and commit
         run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add fonctionnel.md
           git commit -m "Tests fonctionnels à jour"
           
       - name: Update files in repository
         uses: ad-m/github-push-action@master
         with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: tp3
           
           
