name: test-f
on: 
  push:
    branches: tp3
    tags: 
      - v5
    paths-ignore: 
      - '.github/workflows/test-c.yml'
      - 'compilation.md'
      
jobs:
  job_id:
    name: Tests fonctionnels du TP3
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
       - uses: actions/checkout@v2
         with:
          persist-credentials: false 
          fetch-depth: 0

       - name: setup env
         run: |
           sudo apt update
           sudo apt install build-essential

       - name: verification version
         run: |
           echo $OSTYPE
           lsb_release -a 
           gcc -v >& gcc.txt
           cat gcc.txt
           
       - name: compilation
         run: |
          pwd
          make clean
          make
          ls -lash
             
       - name: tests
         run: |
           echo -e \`\`\`\\n > fonctionnel.md
           TZ=America/New_York date >> fonctionnel.md
           echo -e \\n\*\*\*\*\*\*Tests sans arguments\*\*\*\*\*\*\\n >> fonctionnel.md
           echo -e \$ file\.txt \| \.\/tp3\\n >> fonctionnel.md
           cat file.txt | ./tp3 >> fonctionnel.md
           echo -e \\n\*\*\*\*\*\*Tests avec arguments\*\*\*\*\*\*\\n >> fonctionnel.md
           echo -e \$ file\.txt \| \.\/tp3 -i -s -d\\n >> fonctionnel.md
           cat file.txt | ./tp3 -i -s -d >> fonctionnel.md
           echo -e \\n\$ file\.txt \| \.\/tp3 -t -s -d -i\\n >> fonctionnel.md
           cat file.txt | ./tp3 -t -s -d -i >> fonctionnel.md
           echo -e \\n\$ file2\.txt \| \.\/tp3 --t --s --b --d\\n >> fonctionnel.md
           cat file2.txt | ./tp3 --t --s --b --d >> fonctionnel.md
           echo -e \\n\$ file2\.txt \| \.\/tp3 -t\\n >> fonctionnel.md
           cat file2.txt | ./tp3 -t >> fonctionnel.md
           echo -e \\n\*\*\*\*\*\*Tests avec STDIN vide\*\*\*\*\*\*\\n >> fonctionnel.md
           echo -e \$ \.\/tp3 -t\\n >> fonctionnel.md
           ./tp3 -t >> fonctionnel.md
           echo -e \\n\$ \.\/tp3 -i -s -d\\n >> fonctionnel.md
           ./tp3 -i -s -d >> fonctionnel.md
           echo -e \\n\$ \.\/tp3\\n >> fonctionnel.md
           ./tp3 >> fonctionnel.md
           echo -e \\n\`\`\`
           
       - name: Config and commit
         run: |
           git config --global user.email "you@example.com"
           git config --global user.name "Your Name"
           git add fonctionnel.md
           git commit -m "Tests foncitonnels periodique"
           make clean
           
       - name: Update files in repository
         uses: ad-m/github-push-action@master
         with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: tp3
           
           
