name: test-c
on:
  push:
    branches: 
      - tp3
  pull_request:
    branches: 
      - tp3 
    tags:
      - v6
    paths:
      - 'tp3.c'
      - 'outil3.c'
      - 'malib.c'
      - 'outil3.h'
      - 'malib.h'
      - 'test-c.yml'

jobs:
  job_id:
    name: compilation et verification
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          sudo apt update
          sudo apt install build-essential
                
      - name: verification
        run: |
          echo $OSTYPE
          lsb_release -a 
          gcc -v >& gcc.txt
          grep "gcc version 9.3.0" gcc.txt > version.txt
          
      - name: compilation
        run: |
          cd inf3135-a2020
          pwd
          make >& compilation.md


          
           
          
