name: test-f
on: 
  schedule:
    - cron: '0 22 */7 * *'
  push:
    branches: tp3
  pull_request:
    branches: tp3
    tags:
      - v6
    paths:
      - 'tp3.c'
      - 'outil3.c'
      - 'malib.c'
      - 'outil3.h'
      - 'malib.h'
      - '.github/workflows/test-c.yml'
    
jobs:
  job_id:
    name: Tests fonctionnels du TP3
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
       - uses: actions/checkout@v2
         with:
           repository: Nami-R2301/inf3135-a2020
           fetch-depth: 0
       - run: |
          git fetch --prune --unshallow --tags
          echo exit code $?
          git tag --list
 
       - name: setup env
         run: |
           sudo apt update
           sudo apt install build-essential

       - name: verification version
         run: |
           echo $OSTYPE
           lsb_release -a 
           gcc -v >& gcc.txt
           cat gcc.txt
           
       - name: compilation
         run: |
          pwd
          make clean
          make
          ls -lash
             
       - name: tests
         run: |
           echo -e \`\`\`\\n > fonctionnel.md
           TZ=America/New_York date >> fonctionnel.md
           echo -e \\n >> fonctionnel.md
           cat file.txt | ./tp3 >> fonctionnel.md
           cat file.txt | ./tp3 -i -s -d >> fonctionnel.md
           cat file.txt | ./tp3 -t -s -d -i >> fonctionnel.md
           cat file2.txt | ./tp3 --t --s --b --d >> fonctionnel.md
           cat file2.txt | ./tp3 -t >> fonctionnel.md
           ./tp3 -t >> fonctionnel.md
           ./tp3 -i -s -d >> fonctionnel.md
           ./tp3 >> fonctionnel.md
           echo -e \\n\`\`\`
           
       - name: Update files in repository
         uses: ad-m/github-push-action@master
         with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: tp3
           
           
