name: test-c
on:
  push:
    branches: 
      - tp3
  pull_request:
    branches: 
      - tp3 
    tags:
      - v6
    paths:
      - 'tp3.c'
      - 'outil3.c'
      - 'malib.c'
      - 'outil3.h'
      - 'malib.h'
      - 'test-c.yml'

jobs:
  job_id:
    name: compilation et verification
    runs-on: ubuntu-latest
    steps:
      - name: verification
        run: |
          echo $OSTYPE
          gcc -v >& version.txt
          grep "gcc version 9.3.0" > version.txt
      - name: compilation
        if: (success() && contains(searchString, "gcc version 9.3.0"))
        run: |
          cd inf3135-a2020
          pwd
          make >& compilation.md


          
           
          
